[project]
name = "mdma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "autogen-agentchat>=0.6.4",
    "autogen-ext[openai]>=0.6.4",
    "dotenv>=0.9.9",
    "duckduckgo-search>=8.1.1",
]
